FROM golang:1.22.4
EXPOSE 3000 4000
WORKDIR /app

# Copy the go.mod and go.sum files for container 
COPY go.mod go.sum ./  
RUN go mod download
COPY . .

# Install delve for go debugging
RUN CGO_ENABLED=1 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest
RUN CGO_ENABLED=1 go build -gcflags "all=-N -l" -o main . 

CMD [ "/go/bin/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/main"]